require File.expand_path("app/models/item")
require File.expand_path("app/models/weapon")
require File.expand_path("app/models/armor")
require File.expand_path("app/models/aid")
require File.expand_path("app/repositories/iventory_crud")